// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLGVEzGA8DB2K19QiBYU4KwqIP8A20UDg',
    appId: '1:16611665401:web:3384734379079901b80928',
    messagingSenderId: '16611665401',
    projectId: 'databasecoinflow-61857',
    authDomain: 'databasecoinflow-61857.firebaseapp.com',
    storageBucket: 'databasecoinflow-61857.firebasestorage.app',
    measurementId: 'G-TMTSGVQNZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMOFpWOPzpaw0mioKuRTXsEeXgmwCPx3E',
    appId: '1:16611665401:android:33bf149ca766d922b80928',
    messagingSenderId: '16611665401',
    projectId: 'databasecoinflow-61857',
    storageBucket: 'databasecoinflow-61857.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ0Ntl487qD9FZCgYvR4qrsm1H_a7tREA',
    appId: '1:16611665401:ios:7fae6208ccad469cb80928',
    messagingSenderId: '16611665401',
    projectId: 'databasecoinflow-61857',
    storageBucket: 'databasecoinflow-61857.firebasestorage.app',
    iosBundleId: 'com.example.coinflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ0Ntl487qD9FZCgYvR4qrsm1H_a7tREA',
    appId: '1:16611665401:ios:7fae6208ccad469cb80928',
    messagingSenderId: '16611665401',
    projectId: 'databasecoinflow-61857',
    storageBucket: 'databasecoinflow-61857.firebasestorage.app',
    iosBundleId: 'com.example.coinflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLGVEzGA8DB2K19QiBYU4KwqIP8A20UDg',
    appId: '1:16611665401:web:82de494da1690c22b80928',
    messagingSenderId: '16611665401',
    projectId: 'databasecoinflow-61857',
    authDomain: 'databasecoinflow-61857.firebaseapp.com',
    storageBucket: 'databasecoinflow-61857.firebasestorage.app',
    measurementId: 'G-F19C06XKDX',
  );
}
